In [1]:
import numpy as np

array1d = np.array([1,2,3,4,5])
print(array1d)

[1 2 3 4 5]


In [2]:
array2d = np.array([[1,3],[2,4]])
print(array2d)

[[1 3]
 [2 4]]


In [3]:
array3d = np.array([[[1,3],[2,4]], [[5,7],[6,8]]])
print(array3d)

[[[1 3]
  [2 4]]

 [[5 7]
  [6 8]]]


Crea un array unidimensional en saltos de 1 (por defecto)
entre el 0 incluido y el 5 excluido.

In [4]:
np.arange(5)

array([0, 1, 2, 3, 4])

Crea un array unidimensional en saltos de 2
entre el 1 incluido y el 9 excluido.

In [5]:
np.arange(1, 9, 2)

array([1, 3, 5, 7])

Crea un array unidimensional en saltos de 0.2
entre el 3 incluido y el 4 excluido. 

In [6]:
np.arange(3, 4, 0.2)

array([3. , 3.2, 3.4, 3.6, 3.8])

Crea un array unidimensional de 3 elementos
entre el 2 y el 5, ambos incluidos. 

In [7]:
np.linspace(2, 5, 3)

array([2. , 3.5, 5. ])

Crea un array unidimensional de 5 elementos
entre el 4 y el 12, ambos incluidos. 

In [8]:
np.linspace(4, 12, 5)

array([ 4.,  6.,  8., 10., 12.])

Crea una matriz unidimensional de 3 elementos,
todos compuestos por el numero 0.

In [9]:
np.zeros(3)

array([0., 0., 0.])

Crea una matriz de 2 dimensiones de 2 filas y
2 columnas de numeros 0.

In [10]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

Crea una matriz unidimensional de 4 elementos,
todos compuestos por el numero 1.

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

Crea una matriz de 2 dimensiones de 2 filas y
3 columnas de numeros 1.

In [12]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Crea una matriz de tres dimensiones de 2 submatrices 
de 3 filas y 4 columnas de numeros 1.

In [13]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Crea una matriz identidad, en este caso de 4 x 4 

In [14]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Crea una matriz de valores random entre el 0 y el 1, en este caso de 3 x 3

In [15]:
np.random.random((3,3))

array([[0.41071297, 0.07162541, 0.41593992],
       [0.13318006, 0.65712717, 0.91456817],
       [0.3429089 , 0.0032082 , 0.24035954]])

Genera una matriz de 2 x 2 con valores aleatorios enteros entre el 0 y 99.
En este caso, no es necesario utilizar la palabra "size" porque se
proporciona los límites inferior y superior como argumentos posicionales.

In [16]:
np.random.randint(0, 100, (2, 2))

array([[19, 65],
       [74, 26]])

Creamos una matriz de 4 x 3 de valores aleatorios entre el 0 y el 19.
En la función np.random.randint, los límites inferior y superior son 
argumentos posicionales, mientras que la forma de la matriz de salida 
se especifica utilizando la palabra clave "size". Es decir en este caso
si es necesario escribir la palabra "size" ya que se usa solo un argumento
posicional, que es el numero 20 como limite superior.

In [17]:
np.random.randint(20, size=(4,3))

array([[ 3, 13, 19],
       [16,  6,  5],
       [19,  9, 18],
       [16, 12, 12]])

Crea una matriz de 3 x 3 dimensiones con el valor de 5.

In [18]:
np.full((3, 3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

Creamos una matriz de tipo entero con el metodo empty
de 3 x 3, pero sin inicializar sus elementos; luego con
el metodo fill llenamos esa misma matriz con el numero 7

In [19]:
import numpy as np

arreglo = np.empty((3, 3), dtype=int)

arreglo.fill(7)

arreglo

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

Creamos una matriz y podemos ver algunas caracteristicas como:
El numero de dimensiones con ndim

In [20]:
matriz_a = np.array([[2,3,4],[5,6,7]])
matriz_a.ndim

2

El numero de filas y columnas, es decir su forma
de composicion con shape.

In [21]:
matriz_a.shape

(2, 3)

Y el tipo de dato que lo contiene con dtype.

In [22]:
matriz_a.dtype

dtype('int32')