In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
a

# array([1, 2, 3, 4, 5])
# Arrays de 1 dimension (1D) 
# 1) Metodos
np.zeros(3)  #array([0., 0., 0.]) crea un array lleno de ceros; en este caso de 3 ceros

np.ones(4)  #array([1., 1., 1., 1.]) crea un array lleno de unos; en este caso de 4 unos.

np.eye(3)  # crea una matriz identidad de 3 x 3 

# 2) Acceso y slicing
arreglo = np.array([2,4,6,8,10,12])
arreglo[1] # accede al elemento en la posicion del indice especificado en este caso del indice = 1...   4
arreglo[2:4] # nos devuelve un segmento de elementos, en este caso... array([6, 8]) 
arreglo[::-1] # nos devuelve el orden invertido de los elementos en este caso... array([12, 10, 8, 6, 4, 2])

# 3) Operaciones matematicas
valor = 5
arreglo + valor # suma la cantidad de la variable valor a cada elemento... array([7, 9, 11, 13, 15, 17]) 
arreglo - valor # resta la cantidad de la variable valor a cada elemento... array([-3, -1, 1, 3, 5, 7])
arreglo * valor # multiplica la cantidad de la variable valor a cada elemento... array([10, 20, 30, 40, 50, 60])
arreglo / valor # divide la cantidad de la variable valor a cada elemento... array([0.4, 0.8, 1.2, 1.6, 2. ,2.4])
np.sum(arreglo) # suma todos los elementos del array... 42 
np.mean(arreglo) # calcula el promedio de los elementos... 7.0

# 4) Funciones universales(ufuncs), que ofrece una amplia variedad de funciones universales que operan elemento
       # por elemento en un array 
np.sin(arreglo)  # nos da el seno de cada valor del array... array([0.90.., -0.75.., -0.27.., 0.98.., -0.54.., -0.53]) 
np.exp(arreglo)  # nos da el exponencial de cada elemento.. array([7.38..e+00, 5.45..e+01, ..... 1.62..e+05]) 
np.sqrt(arreglo)  # nos da la raiz cuadrada de cada elemento... array([1.41.., 2.  , 2.44.., 2.82.., 3.16.., 3.46..  ]) 

# 5) Funciones de agregacion
np.min(arreglo) # nos da el minimo valor del array... 2
np.max(arreglo) # nos da el maximo valor del array...  12
np.argmin(arreglo) # nos da el indice del valor minimo... 0
np.argmax(arreglo) # nos da el indice del valor maximo... 5

# 6) Funciones de busqueda y filtrado
np.where(arreglo > 4) # nos da el valor de los indices en donde se cumple la condicion pedida
                            # ...array([2, 3, 4, 5], dtype=int64)
arreglo[arreglo > 4]  # filtra elementos basados en una condicion, en este caso los elementos que sean mayor que 4
                            # ...array([6, 8, 10, 12])
                            
np.take(arreglo, [0, 2]) # extrae elementos de un array segun los indices dados ... array([2,6])  
                            
vector = [7, 3, 9, 1, 2, 8] 
vector2 = [1, 4, 0, 2, 2, 5]
# 7) Funciones de manipulacion de datos:
np.sort(vector)  # ordena los elementos en orden ascendente... array([1, 2, 3, 7, 8, 9])
np.argsort(vector)  # obtiene los indices que ordenarian el array... array([3, 4, 1, 0, 5, 2], dtype=int64)
np.unique(vector)  # obtiene valores unicos en el array... array([1, 2, 3, 7, 8, 9])
np.dot(vector, vector2) # obtiene el producto escalar de dos vectores

arr = np.array([[1, 2], [3, 4]])
np.ravel(arr)  # con np.ravel() aplana un array a una dimension ...array[1, 2, 3, 4]

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
np.concatenate((a, b), axis=0)  # concatena dos arrays a lo largo de un eje, en este caso une a y b por filas

# 8) Reduccion y acumulacion:
np.cumsum(vector)  # calcula la suma acumulativa... array([7, 10, 19, 20, 22, 30])
np.cumprod(vector)  # calcula el producto acumulativo... array([7, 21, 189, 189, 378, 3024]) 

# 9) Funciones de estadisticas:
np.mean(vector)  # calcula la media... 5.0
np.median(vector)  # calcula la mediana... 5.0
np.std(vector)  # calcula la desviacion estandar... 3.1091263510296048
np.var(vector)  # calcula la varianza... 9.666666666666666

# 10) Otras funciones importantes:
np.arange(8)  # crea un array de 8 elementos desde el 0 hasta el 7... array([0, 1, 2, 3, 4, 5, 6, 7])
np.arange(5, 10)  # crea un array desde el numero 5 hasta el 9... array([5, 6, 7, 8, 9])
np.arange(2, 15, 3)  # crea un array desde el numero 2 hasta el 14 de 3 en 3... array([2, 5, 8, 11, 14])
np.arange(3, 4, 0.2) # crea un array desde el 3 hasta 3.8 de 0.2 en 0.2... array([3. , 3.2, 3.4, 3.6, 3.8])

np.linspace(2, 5, 3)  # crea un array de entre el 2 y el 5 de 3 elementos... array([2. , 3.5, 5. ])
np.linspace(4, 12, 5)  # crea un array entre el 4 y el 12 de 5 elementos... array([4., 6., 8., 10., 12. ])

np.random.rand(3, 4) # crea un array de numeros aleatorios de 3 filas por 4 columnas
np.random.randn(4) # crea un array de 4 numeros aleatorios de una distribucion normal
np.random.randint(1, 100, 10) # genera 10 numeros aleatorios entre el 1 y el 100

In [4]:
#array([1., 1., 1., 1.]) crea un array lleno de unos; en este caso de 4 unos.

np.ones(4)

array([1., 1., 1., 1.])

2) Acceso y slicing

In [5]:
arreglo = np.array([2,4,6,8,10,12])

# Accede al elemento en la posicion del indice especificado en este caso del indice = 1

arreglo[1]

4

In [6]:
# Nos devuelve un segmento de elementos, desde el indice 2 al indice 3

arreglo[2:4]

array([6, 8])

In [7]:
 # Nos devuelve el mismo array con el orden invertido de los elementos

arreglo[::-1]

array([12, 10,  8,  6,  4,  2])

3) Operaciones matematicas

In [8]:
valor = 5

# Suma la cantidad de la variable valor a cada elemento del array arreglo
# Recordemos que: arreglo = np.array([2,4,6,8,10,12]) 

arreglo + valor

array([ 7,  9, 11, 13, 15, 17])

In [8]:
# Resta la cantidad de la variable valor a cada elemento del arreglo

arreglo - valor

array([-3, -1,  1,  3,  5,  7])

In [9]:
# Multiplica la cantidad de la variable valor a cada elemento del arreglo

arreglo * valor

array([10, 20, 30, 40, 50, 60])

In [10]:
# Divide la cantidad de la variable valor a cada elemento del arreglo

arreglo / valor

array([0.4, 0.8, 1.2, 1.6, 2. , 2.4])

In [11]:
# Suma todos los elementos del array arreglo

np.sum(arreglo)

42

In [13]:
# Obtiene el producto de todos los elementos del arreglo

np.prod(arreglo)

46080

4) Funciones matematicas universales

In [14]:
np.sin(arreglo)

array([ 0.90929743, -0.7568025 , -0.2794155 ,  0.98935825, -0.54402111,
       -0.53657292])

In [15]:
np.sqrt(arreglo)

array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162])

5) Otras funciones

In [18]:
valores = np.array([7,2,9,5,12,3,8])

np.min(valores)

2

In [19]:
np.max(valores)

12

In [20]:
np.argmin(valores)

1

In [21]:
np.argmax(valores)

4

In [2]:
import numpy as np

arreglo_random = np.random.randint(1, 21, size=(8, 5))
arreglo_random

array([[ 9, 12, 10,  9,  2],
       [12, 11,  3,  8, 17],
       [ 7,  1,  1, 18, 16],
       [12,  6,  1, 17,  2],
       [19, 19, 15, 18, 17],
       [ 3,  7, 11,  5, 19],
       [19,  3,  3, 14, 15],
       [ 2,  2,  8, 17, 16]])

Referencia youtube: "El tutorial más importante sobre NumPy" 
                canal: A2 Ciencia de Datos min 32' 35''

Selecciona el cuarto valor en el segundo array del arreglo_random

In [3]:
arreglo_random[1, 3]

11

Selecciona el segundo valor en los arrays con indice 3, 4, 5 del arreglo_random

In [4]:
arreglo_random[3:6,1]

array([9, 8, 7])

Selecciona los tres primeros valores de los arrays con indice 4, 5, 6 del arreglo_random 

In [5]:
arreglo_random[4:7, :3]

array([[20,  8, 18],
       [15,  7,  3],
       [11,  6, 15]])