Del archivo arrays_creacion.ipynb nos falto ver el metodo reshape.
Aqui algunos ejemplos

In [2]:
import numpy as np

arreglo = np.array([2,4,6,8,10,12])

arreglo.reshape(2,3) # 2 filas por 3 columnas

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [3]:
arreglo.reshape(3,2) # 3 filas por 2 columnas

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

Con la funcion arange(36) creamos un array unidimensional entre el 0 y
el 35, en saltos de 1.

In [4]:
arr1 = np.arange(36)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

Con el metodo reshape le damos otra forma a la matriz arr1
de 6 x 6 osea 6 filas por 6 columnas.

In [5]:
arr1.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

Con el metodo reshape le damos otra forma a la matriz arr1
de 4 x 9 osea 4 filas por 9 columnas.

In [6]:
arr1.reshape(4,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

Ahora con el metodo reshape le damos otra forma a la matriz arr1
de 3 x 4 x 3 osea 3 submatrices y cada una de ellas de 4 filas
por 3 columnas.

In [7]:
arr1.reshape(3,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

Creamos la matriz m1 de 2 filas y 3 columnas.

In [8]:
m1 = np.array([[4, -5, 3],[8, 7, -11]])
m1

array([[  4,  -5,   3],
       [  8,   7, -11]])

Creamos la matriz m2 de 2 filas y 3 columnas.

In [9]:
m2 = np.array([[3,2,-7], [-4, 5, 14]])
m2

array([[ 3,  2, -7],
       [-4,  5, 14]])

Sumamos ambas matrices con el operador '+'

In [10]:
m1+m2

array([[ 7, -3, -4],
       [ 4, 12,  3]])

Tambien las podemos sumar con el metodo add.

In [11]:
msuma = np.add(m1, m2)
msuma

array([[ 7, -3, -4],
       [ 4, 12,  3]])

Restamos ambas matrices con el operador '-'

In [12]:
m1-m2

array([[  1,  -7,  10],
       [ 12,   2, -25]])

Tambien los podemos restar con el metodo subtract.

In [13]:
mresta = np.subtract(m1, m2)
mresta

array([[  1,  -7,  10],
       [ 12,   2, -25]])

Multiplicamos ambas matrices valor por valor con el operador '*'.
Ojo: no confundir con el producto de matrices.

In [14]:
m1*m2

array([[  12,  -10,  -21],
       [ -32,   35, -154]])

La misma operacion anterior la podemos realizar mediante la funcion multiply.

In [15]:
mmultiplicacion = np.multiply(m1, m2)
mmultiplicacion

array([[  12,  -10,  -21],
       [ -32,   35, -154]])

Dividimos ambas matrices (valor por valor) mediante el operador '/'

In [16]:
m1/m2

array([[ 1.33333333, -2.5       , -0.42857143],
       [-2.        ,  1.4       , -0.78571429]])

La misma operacion anterior la podemos realizar mediante la funcion divide.

In [17]:
mdivision = np.divide(m1, m2)
mdivision

array([[ 1.33333333, -2.5       , -0.42857143],
       [-2.        ,  1.4       , -0.78571429]])

Creamos la matriz array1 de 2 filas y 3 columnas.

In [18]:
array1 = np.array([[3, -7, 4], [11, 2, -5]])
array1

array([[ 3, -7,  4],
       [11,  2, -5]])

Creamos la matriz array2 de 3 filas y 2 columnas.

In [19]:
array2 = np.array([[2, 9], [1, -5], [3,-7]])
array2
                  

array([[ 2,  9],
       [ 1, -5],
       [ 3, -7]])

Multiplicamos ambas matrices mediante el metodo dot

In [20]:
array_dot = np.dot(array1, array2)
array_dot

array([[ 11,  34],
       [  9, 124]])

Otra forma de multiplicar ambas matrices

In [21]:
array1.dot(array2)

array([[ 11,  34],
       [  9, 124]])

Aqui una tercera forma de multiplicar ambas matrices, usando el operador '@'

In [22]:
array1 @ array2

array([[ 11,  34],
       [  9, 124]])

Otro ejemplo, creamos la matriz array3 de 2 filas y 3 columnas.

In [23]:
array3 =np.array([[1, -2, 3], [1, 0, -1]])
array3

array([[ 1, -2,  3],
       [ 1,  0, -1]])

Ahora creamos la matriz array4 de 3 filas y 1 columna.

In [24]:
array4 = np.array([[4], [5], [6]])
array4

array([[4],
       [5],
       [6]])

Multiplicamos ambas matrices

In [25]:
array3.dot(array4)

array([[12],
       [-2]])

Calculamos la transpuesta de la matriz array3

In [26]:
arr_tranp =  np.transpose(array3)
arr_tranp

array([[ 1,  1],
       [-2,  0],
       [ 3, -1]])

Volvemos a ver la matriz array3.

In [27]:
array3

array([[ 1, -2,  3],
       [ 1,  0, -1]])

Suma los elementos de un array, (axis=0) suma las columnas.

In [28]:
array3.sum(axis=0)

array([ 2, -2,  2])

Suma los elementos de un array, (axis=1) suma las filas.

In [29]:
array3.sum(axis=1)

array([2, 0])

Con el metodo max y el parametro axis=0 obtenemos los valores maximos
de cada columna.

In [30]:
array3.max(axis=0)

array([1, 0, 3])

Con el metodo max y el parametro axis=1 obtenemos los valores maximos
de cada fila.

In [31]:
array3.max(axis=1)

array([3, 1])

Con el metodo min y el parametro axis=0 obtenemos los valores minimos
de cada columna.

In [32]:
array3.min(axis=0)

array([ 1, -2, -1])

Con el metodo min y el parametro axis=1 obtenemos los valores minimos
de cada fila.

In [33]:
array3.min(axis=1)

array([-2, -1])

Con el metodo argmax y el parametro axis=0 obtenemos los indices cuyos valores 
son maximos de cada columna.

In [34]:
array3.argmax(axis=0)

array([0, 1, 0], dtype=int64)

Obtiene el promedio de cada columna (axis=0)

In [35]:
array3.mean(axis=0)

array([ 1., -1.,  1.])

Obtiene el promedio de cada fila (axis=1)

In [36]:
array3.mean(axis=1)

array([0.66666667, 0.        ])

Creamos la matriz array5

In [37]:
array5 = np.array([[2, -5, 3], [-1, 4, -10]])
array5

array([[  2,  -5,   3],
       [ -1,   4, -10]])

Tambien se puede operar un escalar (numero) con una matriz.
En este caso sumamos el numero 2 a la matriz.

In [39]:
2 + array5

array([[ 4, -3,  5],
       [ 1,  6, -8]])

Ahora restamos la matriz array5 al numero 10

In [40]:
array5 - 10

array([[ -8, -15,  -7],
       [-11,  -6, -20]])

Multiplicamos ahora el numero 5 a la matriz array5.

In [41]:
5 * array5

array([[ 10, -25,  15],
       [ -5,  20, -50]])

Dividimos la matriz array5 entre 10.

In [42]:
array5 / 10

array([[ 0.2, -0.5,  0.3],
       [-0.1,  0.4, -1. ]])

Creamos la matriz cuadrada de 3 x 3, array6.

In [44]:
array6 = np.array([[3, -7, 4], [2, 1, -9], [12, 7, 8]])
array6

array([[ 3, -7,  4],
       [ 2,  1, -9],
       [12,  7,  8]])

Calculamos la matriz inversa de array6

In [45]:
matriz_inversa = np.linalg.inv(array6)
matriz_inversa

array([[ 0.06519743,  0.07713499,  0.05417815],
       [-0.11386593, -0.02203857,  0.03213958],
       [ 0.00183655, -0.09641873,  0.01561065]])